### ISSUE TITLE
Design the self-report edit page - image section

### ISSUE THREAD

**Issue by lima01** [1thing-org/hatecrimetracker-frontend#73]
Need to allow admin to select/deselect images /video to show at the front-end.

**Comment by yuukah713** [comment]
https://www.figma.com/design/qhJANtbj3OJgJWwBYFqzfF/Hate-Crime-Tracker-Design?node-id=2722-434&t=qCsJpr7xmgLchhym-0


![Image](https://github.com/1thing-org/hatecrimetracker-frontend/assets/56624857/f8eafb74-0618-4bd5-9c1b-a784c5a146e5)
